#%RAML 1.0
title: GetEmployeeList
mediaType:
  - application/json
protocols:
  - HTTP
/createemployee:
  post:
    responses:
      "201": {}
/getemplist:
  get:
    responses:
      "200": {}
    securedBy: []
securedBy: []
